version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: eventosQR
    volumes:
      - mongo-data:/data/db

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "5000:3000"
    depends_on:
      - login
      - talleres
      - participantes
      - eventos
      - asistencia

  login:
    build: ./services
    container_name: login
    ports:
      - "5001:4001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventosQR
    depends_on:
      - mongo

  talleres:
    build: ./services
    container_name: talleres
    ports:
      - "5002:4002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventosQR
    depends_on:
      - mongo

  participantes:
    build: ./services
    container_name: participantes
    ports:
      - "5003:4003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventosQR
    depends_on:
      - mongo

  eventos:
    build: ./services
    container_name: eventos
    ports:
      - "5004:4004"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventosQR
    depends_on:
      - mongo

  asistencia:
    build: ./services
    container_name: asistencia
    ports:
      - "5005:4005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventosQR
    depends_on:
      - mongo

volumes:
  mongo-data:
